window.CIBERSEGURIA_CONTENT = Object.freeze({
  templates: [
    { id: 'TEMPLATE_01', number: '01', short: 'Gobierno', title: 'Modelo de gobierno - Sistema Multiagente de IA', description: 'Define roles, responsabilidades, supervisión humana y reglas de decisión antes de activar el sistema.', url: 'https://docs.google.com/document/d/1ed7r1QO1rm29Cl_yI-2cIlpcyyNG4XVR/edit?usp=sharing&ouid=104003199436133664465&rtpof=true&sd=true' },
    { id: 'TEMPLATE_02', number: '02', short: 'Arquitectura', title: 'Arquitectura de seguridad - Sistema Multiagente de IA', description: 'Documenta agentes, herramientas, identidades, fronteras de confianza y rutas de datos.', url: 'https://docs.google.com/document/d/1778Zj-qR5ZSzc8mcUfZQYbcKKuJCmnt0/edit?usp=sharing&ouid=104003199436133664465&rtpof=true&sd=true' },
    { id: 'TEMPLATE_03', number: '03', short: 'Riesgos', title: 'Análisis de riesgos - Sistema Multiagente de IA', description: 'Identifica escenarios de abuso, fallos en cadena, impactos y medidas de tratamiento.', url: 'https://docs.google.com/document/d/1dVcb_L1RtYP47pLTacQ8tgbf3n-0dG53/edit?usp=sharing&ouid=104003199436133664465&rtpof=true&sd=true' },
    { id: 'TEMPLATE_04', number: '04', short: 'Privacidad', title: 'Evaluación de impacto en privacidad y protección de datos - Sistema Multiagente de IA', description: 'Evalúa necesidad, proporcionalidad, flujos de información y garantías para las personas.', url: 'https://docs.google.com/document/d/1XFCSdCaCQwap_grURB_JF2gBv_2npcov/edit?usp=sharing&ouid=104003199436133664465&rtpof=true&sd=true' },
    { id: 'TEMPLATE_05', number: '05', short: 'Controles', title: 'Catálogo de controles - Sistema Multiagente de IA', description: 'Convierte los riesgos en salvaguardas técnicas, organizativas y operativas verificables.', url: 'https://docs.google.com/document/d/1_1NnZWO3QIgzmcqPslmGUZcQ_yrGB9RM/edit?usp=sharing&ouid=104003199436133664465&rtpof=true&sd=true' },
    { id: 'TEMPLATE_06', number: '06', short: 'Trazabilidad', title: 'Matriz de trazabilidad - Sistema Multiagente de IA', description: 'Relaciona requisitos, riesgos, controles, pruebas, evidencias y responsables.', url: 'https://docs.google.com/document/d/1SkoldALAHfHk9vNwDV-F0gLQ7SGK99qF/edit?usp=sharing&ouid=104003199436133664465&rtpof=true&sd=true' },
    { id: 'TEMPLATE_07', number: '07', short: 'Implantación', title: 'Memoria de implantación, decisiones y trazabilidad - Sistema Multiagente de IA', description: 'Reúne la configuración final, las decisiones tomadas y la evidencia necesaria para operar y auditar.', url: 'https://docs.google.com/document/d/1MmR5fViwUgmfT6QRaTABjpnhuhNxqNlp/edit?usp=sharing&ouid=104003199436133664465&rtpof=true&sd=true' }
  ],
  chamulleando: [
    { id: 'CHAMULLEANDO_01', number: '01', title: 'Predicciones top3 trabajos irremplazables por la IA', description: 'Predicción sobre los trabajos que, por su esencia puramente humana, son imposibles de automatizar o transferir a una máquina.', date: '13 abril 2026', dateTime: '2026-04-13T12:58:41+00:00', image: 'https://substackcdn.com/image/fetch/$s_!9jqg!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fdbaef9dc-3143-419f-88a5-055889d9e38f_567x378.jpeg', url: 'https://ciberseguria.substack.com/p/predicciones-top3-trabajos-irremplazables' },
    { id: 'CHAMULLEANDO_02', number: '02', title: 'Por qué el “Role-Play” es el talón de Aquiles de la IA', description: 'Sobre el funcionamiento de los LLM bajo roleos de personajes.', date: '7 marzo 2026', dateTime: '2026-03-07T09:22:33+00:00', image: 'https://substackcdn.com/image/fetch/$s_!pJbF!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F444ac1c9-ca94-46e3-a28a-18c1f590224d_977x994.png', url: 'https://ciberseguria.substack.com/p/por-que-el-role-play-es-el-talon' },
    { id: 'CHAMULLEANDO_03', number: '03', title: '¿Y si PLURIBUS es el AGI en el metaverso?', description: 'Con spoilers: por qué la serie del creador de Breaking Bad tiene similitudes con la Inteligencia Artificial General.', date: '5 enero 2026', dateTime: '2026-01-05T10:19:50+00:00', image: 'https://substackcdn.com/image/fetch/$s_!dwo5!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F4fc4b064-9655-4b69-a803-f9e868c39619_2281x1063.png', url: 'https://ciberseguria.substack.com/p/y-si-pluribus-es-el-agi-en-el-metaverso' }
  ],
  caraB: [
    { id: 'cara-b-01', title: '90 Minutos de Ventaja', type: 'Ficción interactiva', description: 'Una ficción interactiva cyberpunk de fútbol, robos y burocracia automatizada.', url: 'https://noventa-minutos.jmexposito.chatgpt.site', status: 'live', statusLabel: 'Disponible', featured: true, placeholder: false },
    { id: 'cara-b-02', title: 'El Elegido: La Cadena', type: 'Ficción interactiva', description: 'Una ficción ambientada en 2097 para reconocer fallos de confianza y manipulación del lenguaje en agentes de IA.', url: 'https://el-elegido-la-cadena.jmexposito.chatgpt.site', status: 'live', statusLabel: 'Disponible', featured: false, placeholder: false },
    { id: 'cara-b-03', title: 'Chema Pelis', type: 'Cine + IA', description: 'Un recomendador de cine personalizado que cruza gustos de Letterboxd, época y tipo de película para ayudarte a elegir qué ver.', url: 'https://chema-pelis.jmexposito.chatgpt.site', status: 'live', statusLabel: 'Disponible', featured: false, placeholder: false },
    { id: 'cara-b-04', title: 'PEPI.EXE', type: 'Aventura narrativa', description: 'Un juego narrativo sobre perros, personas y los problemas que aparecen cuando un paseo normal deja de serlo.', url: 'https://pepi-exe.jmexposito.chatgpt.site', status: 'live', statusLabel: 'Disponible', featured: false, placeholder: false }
  ],
  latest: [
    { id: 'ARTICLE_05', title: 'GOVERNANCE BY DESIGN. CÓMO CONSTRUIR UN ECOSISTEMA DE AGENTES DE IA (II)', description: 'Sobre mi experiencia implementando un laboratorio de agentes de IA (segunda parte).', date: '30 julio 2026', dateTime: '2026-07-30T09:02:37+00:00', image: 'https://substackcdn.com/image/fetch/$s_!lOt0!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fbd3f9c87-72dd-4b35-9dc7-07d83bec0093_1448x1086.png', url: 'https://ciberseguria.substack.com/p/governance-by-design-como-construir-742' },
    { id: 'ARTICLE_04', title: 'GOVERNANCE BY DESIGN. CÓMO CONSTRUIR UN ECOSISTEMA DE AGENTES DE IA (I)', description: 'Sobre mi experiencia implementando un laboratorio de agentes de IA.', date: '21 julio 2026', dateTime: '2026-07-21T15:32:12+00:00', image: 'https://substackcdn.com/image/fetch/$s_!gyka!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3e800982-ee29-48cd-8841-790efda9fb8c_1448x1086.png', url: 'https://ciberseguria.substack.com/p/governance-by-design-como-construir' },
    { id: 'ARTICLE_03', title: 'Fable 5: cada vez es más difícil comprender a las IAs y auditarlas se va a poner feo', description: 'DATA DATA DATA. GO.', date: '6 julio 2026', dateTime: '2026-07-06', image: 'https://substackcdn.com/image/fetch/$s_!2PgD!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3d303571-05f4-4dd5-8900-13fe5348e8a4_634x483.png', url: 'https://substack.com/@ciberseguria/p-205494368?utm_source=ciberseguria.com' },
    { id: 'ARTICLE_02', title: 'GPT-5.5-Cyber: Entre la necesidad operativa y la dependencia estratégica en la Unión Europea', description: 'Sobre Mythos made in ChatGPT y los riesgos a los que se enfrenta Europa.', date: '27 mayo 2026', dateTime: '2026-05-26T22:14:48+00:00', image: 'https://substackcdn.com/image/fetch/$s_!FkVQ!,f_auto,q_auto:best,fl_progressive:steep/https%3A%2F%2Fciberseguria.substack.com%2Ftwitter%2Fsubscribe-card.jpg%3Fv%3D-1915528558%26version%3D9', url: 'https://ciberseguria.substack.com/p/gpt-55-cyber-entre-la-necesidad-operativa' },
    { id: 'ARTICLE_01', title: 'Nuestra seguridad digital era un castillo de naipes (y la IA acaba de estornudar)', description: 'Lo de Anthropic con la beta de Mythos no ha sido un lanzamiento propiamente dicho: se ha convertido en un funeral.', date: '29 abril 2026', dateTime: '2026-04-29', image: 'https://substackcdn.com/image/fetch/$s_!RAUf!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F55555352-900c-4351-9869-ede1a51ef059_463x343.png', url: 'https://substack.com/@ciberseguria/p-195875280?utm_source=ciberseguria.com' },
    { id: 'ARTICLE_CONECTA35', title: 'Conéctate35: la respuesta española para mantenernos en línea cuando todo se apaga', description: 'En un contexto de ciberataques, cortes de cables submarinos y caos digital, la Conéctate35 ofrece una alternativa nacional para asegurar la conectividad crítica de infraestructuras', date: '25 junio 2025', dateTime: '2025-06-25T07:32:11+00:00', image: 'https://substackcdn.com/image/fetch/$s_!vmV-!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fc4d3e6fc-f8b7-4a05-ac88-104aa53677b3_789x528.png', url: 'https://ciberseguria.substack.com/p/conectate35-la-respuesta-espanola' }
  ]
});
